Flex-NFT-Marketplace/Flex-Marketplace-Contract

.github/workflows/build.yml, .github/workflows/test.yml, .gitignore, flex_marketplace/Scarb.lock, flex_marketplace/Scarb.toml, flex_marketplace/src/lib.cairo, flex_marketplace/src/marketplace/market_place.cairo
scarb fmt
scarb build
snforge test
=> added CI workflows for build + test + cairo 2.4.0 deps

flex_marketplace/src/lib.cairo, flex_marketplace/src/marketplace/market_place.cairo, flex_marketplace/src/marketplace/royalty_fee_manager.cairo, flex_marketplace/src/marketplace/royalty_fee_registry.cairo
=> RoyaltyFeeManager in cairo1

flex_marketplace/src/marketplace/transfer_manager_ERC1155.cairo
=> transfer manager erc 1155 to cairo1

flex_marketplace/src/marketplace/marketplace.cairo, flex_marketplace/src/marketplace/transfer_manager_ERC721.cairo
=> implemented erc721 transfer manager

.gitignore, flex_marketplace/src/marketplace/transfer_selector_NFT.cairo
=> Transfer selector nft

.gitignore, flex_marketplace/src/marketplace/signature_checker2.cairo
=> Signature checker2

.gitignore, flex_marketplace/src/marketplace/royalty_fee_registry.cairo
=> Royalty fee registry functions bodies

.gitignore, flex_marketplace/src/marketplace/execution_manager.cairo
=> added bodies for functions

.gitignore, flex_marketplace/Scarb.toml, flex_marketplace/src/marketplace/currency_manager.cairo, flex_marketplace/src/marketplace/marketplace.cairo, flex_marketplace/src/marketplace/royalty_fee_manager.cairo, flex_marketplace/src/marketplace/signature_checker2.cairo, flex_marketplace/src/marketplace/transfer_manager_ERC1155.cairo, flex_marketplace/src/marketplace/transfer_selector_NFT.cairo, flex_marketplace/tests/currency_manager_test.cairo, flex_marketplace/tests/execution_manager_test.cairo, flex_marketplace/tests/marketplacet_test.cairo, flex_marketplace/tests/royalty_fee_managen_test.cairo, flex_marketplace/tests/royalty_fee_registry_test.cairo, flex_marketplace/tests/signature_checker2_test.cairo, flex_marketplace/tests/transfer_manager_erc1155_test.cairo, flex_marketplace/tests/transfer_manager_erc721_test.cairo, flex_marketplace/tests/transfer_selector_nft_test.cairo, flex_marketplace/tests/utils.cairo
added all functions headers for test and fails, will open issues once merged
=> Tests setup

.github/workflows/test.yml, flex_marketplace/src/lib.cairo, flex_marketplace/src/marketplace/transfer_manager_ERC1155.cairo, flex_marketplace/src/mocks/erc1155.cairo, flex_marketplace/tests/transfer_manager_erc1155_test.cairo, flex_marketplace/tests/utils.cairo
=> Added Tests For Transfer Manager ERC1155

flex_marketplace/tests/marketplace_test.cairo, flex_marketplace/tests/utils.cairo
Merge this before merging other PRs
=> fix failing CI on main branch

README.md
Improved README for stakingpool contract
resolves #89
=> docs: add documentation on stakingpool

stakingpool/Scarb.toml, stakingpool/tests/lib.cairo, stakingpool/tests/test_flex_staking_pool.cairo
Writing unit tests for FlexStakingPool, solves issue #79
=> test: Write unit tests for FlexStakingPool

marketplace/src/HighestBidderAuctionSale.md, marketplace/src/strategy_highest_bidder_auction_sale.cairo
This Pr Implements the Strategy Highest Bidder Auction Sale for issue #85
=> feat: HighestBidderAuctionSale

marketplace/scripts/deployment.ts
The deployment of contracts with or without constructors is handled in one function, deployContract.
A separate function, initializeContract, is responsible for initializing contracts.
Repetitive tasks like adding currency or updating selectors are managed by handleContractAction, which simplifies adding new actions.
The contractsToDeploy array allows easy addition or modification of contracts in the deployment sequence.
Fixed #78
=> Refactor deployment script for cleaner code

README.md
=> docs: update README.md for openedition contracts

marketplace/src/strategy_private_sale.cairo
=> feat: implement strategy_private_sale contract

README.md
resolves issue: #87 
README for marketplace contracts
=> documentation on marketplace

flex_haus/Scarb.toml, flex_haus/tests/test_flex_haus_collectible.cairo
=> feat: unit tests for Flex Haus Collectible

marketplace/src/lib.cairo, marketplace/src/mocks/randomness.cairo, marketplace/src/strategy_yolo_buy.cairo, marketplace/src/utils/order_types.cairo, marketplace/tests/lib.cairo, marketplace/tests/test_strategy_yolo.cairo
Resolves #117 
@0xandee ready for review.
1. Updated yolobuy to allow multiple orders, ensuring order can be tracked consistently, without data loss.
2. Added events to the contract.
2. Tests 80%
=> Continue Yolo Buy

README.md, marketplace/README.md, openedition/README.md, stakingpool/README.md
=> README file

flex_haus/Scarb.toml, flex_haus/tests/test_flex_haus_factory.cairo
- Test constructor.
- Test create collectible.
- Test create drop.
- Test claim collectible.
- Add helper functions for contract deployment and setup.
- Use `snforge_std` for testing utilities.
[*] Test
=> unit tests for Flex Haus Factory
